#define IDC_STATIC -1
#define IDC_MYICON 2
#define IDD_WINTEST_DIALOG 102
#define IDD_ABOUTBOX 103
#define IDS_APP_TITLE 103
#define IDM_ABOUT 104
#define IDM_EXIT 105
#define IDI_WINTEST 107
#define IDI_SMALL 108
#define IDC_WINTEST 109
#define _APS_NEXT_SYMED_VALUE 110
#define IDR_MAINFRAME 128
#define _APS_NEXT_RESOURCE_VALUE 129
#define _APS_NO_MFC 130
#define _APS_NEXT_CONTROL_VALUE 1000
#define _APS_NEXT_COMMAND_VALUE 32771

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 129
#define _APS_NEXT_COMMAND_VALUE 1
#define _APS_NEXT_CONTROL_VALUE 110
#define _APS_NEXT_SYMED_VALUE 32772
#endif
#endif
